config/routes.rb
Rails.application.routes.draw do
  get 'invite/invite_user'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :crawls, only: [:index, :show, :create, :update, :destroy, :new] do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:show, :create, :edit, :update, :destroy]
  resources :bars, only: [:index, :show, :create, :edit, :update] do
    collection do
      get 'autocomplete/:query' => :autocomplete
    end
  end
  resources :drinks, only: [:new, :create]

  post 'invites', to: 'invites#invite_user'
  get 'invites/:id', to: 'invites#get_invites'

  root to: 'crawls#index'

end

app/views/layouts/_footer.html.erb
<div id="footer" class="hidden-footer">
  <div class="container">
    <div class="row">
      <div class="social-icons-list-flex">
        <ul class="social-icons text-center">
          <li class="social-list">
            <a href="https://github.com/ianvdhSBM/pub_crawl_final" target="_blank">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="social-list">
            <a href="https://github.com/ianvdhSBM/pub_crawl_final" target="_blank">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="social-list">
            <a href="https://github.com/ianvdhSBM/pub_crawl_final" target="_blank">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <br/>
        <div class="credits">
          <p class="contact-paragraph">Created by Ian Van Den Heuvel, Paul Iogna, and Hanna Jones<br/> &copy; Lighthouse Labs, February 2016</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top" id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">hopper</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/" class="navigation-item">hops</a></li>
        <% if user %>
          <li><%= link_to new_crawl_path, :class => "navigation-item" do %><i class="fa fa-beer fa-lg"></i> create new hop<% end %></li>
        <% end %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.invites.any? %>
            <li><%= link_to user_path(current_user.id), :class => "navigation-item" do %><i class="fa fa-users fa-lg"></i> invites <% end %></li>
          <% end %>
          <li><%= link_to user_path(current_user.id), :class => "navigation-item" do %><i class="fa fa-user fa-lg"></i> my profile<% end %></li>
          <li><%= link_to destroy_user_session_path, :method => :delete, :class => "navigation-item" do %><i class="fa fa-sign-out fa-lg"></i> sign out<% end %></li>
          <li id="contact"><a class="navigation-item">contact</a></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to new_user_registration_path, :class => "navigation-item" do %><i class="fa fa-users fa-lg"></i> sign up!<% end %></li>
          <li><%= link_to new_user_session_path, :class => "navigation-item" do %><i class="fa fa-sign-in fa-lg"></i> sign in<% end %></li>
          <li id="contact"><a class="navigation-item">contact</a></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PubCrawlFinal</title>
    <!-- google fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:700,900' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google maps -->
    <script src="http://maps.google.com/maps/api/js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.12/gmaps.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render :partial => 'layouts/navbar', :locals => {:user => current_user} %>
   
        <%= yield %>

    <%= render :partial => 'layouts/footer' %>
  </body>
  
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1768705696686469',
        xfbml      : true,
        version    : 'v2.5'
      });
    };

    (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    $(document).ready(function() {
      $("#contact").on('click', function() {
        $("#footer").slideToggle("slow");
      })
    })
  </script>

</html>